=== raidplaner/Core/XSD/characterProfileMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml files which install, update or delete character profile menus. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://daries.dev" targetNamespace="http://daries.dev" elementFormDefault="qualified">
    <!-- include types -->
    <xs:include schemaLocation="types.xsd" />

    <!-- data element -->
    <xs:element name="data">
        <xs:complexType>
            <xs:all>
                <xs:element name="import" type="import" minOccurs="0" />
                <xs:element name="delete" type="delete" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <!-- import element -->
    <xs:complexType name="import">
        <xs:sequence>
            <xs:element name="characterprofilemenuitem" type="characterprofilemenuitem_import" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- delete element -->
    <xs:complexType name="delete">
        <xs:sequence>
            <xs:element name="characterprofilemenuitem" type="characterprofilemenuitem_delete" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- delete character profile menu item element -->
    <xs:complexType name="characterprofilemenuitem_delete">
        <xs:attribute name="name" type="daries_varchar" use="required" />
    </xs:complexType>

    <!-- imported/updated character profile menu item element -->
    <xs:complexType name="characterprofilemenuitem_import">
        <xs:complexContent>
            <xs:extension base="characterprofilemenuitem_delete">
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="classname" type="daries_varchar" minOccurs="1" />
                    <xs:element name="options" type="xs:string" minOccurs="0" />
                    <xs:element name="permissions" type="xs:string" minOccurs="0" />
                    <xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== raidplaner/Core/rpCharacterProfileMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://daries.info/XSD/rp/characterProfileMenu.xsd">
    <import>
        <characterprofilemenuitem name="about">
            <classname>rp\system\menu\character\profile\content\AboutCharacterProfileMenuContent</classname>
            <showorder>1</showorder>
        </characterprofilemenuitem>
        <characterprofilemenuitem name="points">
            <classname>rp\system\menu\character\profile\content\PointsCharacterProfileMenuContent</classname>
            <showorder>2</showorder>
        </characterprofilemenuitem>
        <characterprofilemenuitem name="item">
            <classname>rp\system\menu\character\profile\content\ItemCharacterProfileMenuContent</classname>
            <showorder>3</showorder>
        </characterprofilemenuitem>
        <characterprofilemenuitem name="raid">
            <classname>rp\system\menu\character\profile\content\RaidCharacterProfileMenuContent</classname>
            <showorder>4</showorder>
        </characterprofilemenuitem>
        <characterprofilemenuitem name="raid.attendance">
            <classname>rp\system\menu\character\profile\content\RaidAttendanceCharacterProfileMenuContent</classname>
            <showorder>5</showorder>
        </characterprofilemenuitem>
    </import>
</data>
